FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["BooksWagonApplication.csproj", "./"]
RUN dotnet restore "./BooksWagonApplication.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "BooksWagonApplication.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BooksWagonApplication.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BooksWagonApplication.dll"]  # Corrected typo here

