// <auto-generated />
using System;
using BooksWagonApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksWagonApplication.Migrations
{
    [DbContext(typeof(BookShopContext))]
    [Migration("20230203032225_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BooksWagonApplication.Models.ArtsPhotography", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Bindingtype")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("BookName")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("BookTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Languagetype")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("SubTypeOfBook")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("TypeOfBook")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("BookId")
                        .HasName("PK__ArtsPhot__3DE0C207F2C47ACD");

                    b.HasIndex("BookTypeId");

                    b.ToTable("ArtsPhotography", (string)null);
                });

            modelBuilder.Entity("BooksWagonApplication.Models.ArtsPhotographyDatum", b =>
                {
                    b.Property<int>("BookTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SubTypeOfBook")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("TypeOfBook")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("BookTypeId")
                        .HasName("PK__Arts_Pho__259BDEF3FA763D7F");

                    b.ToTable("Arts_PhotographyData", (string)null);
                });

            modelBuilder.Entity("BooksWagonApplication.Models.ArtsPhotography", b =>
                {
                    b.HasOne("BooksWagonApplication.Models.ArtsPhotographyDatum", "BookType")
                        .WithMany("ArtsPhotographies")
                        .HasForeignKey("BookTypeId")
                        .HasConstraintName("FK_ArtsBookType");

                    b.Navigation("BookType");
                });

            modelBuilder.Entity("BooksWagonApplication.Models.ArtsPhotographyDatum", b =>
                {
                    b.Navigation("ArtsPhotographies");
                });
#pragma warning restore 612, 618
        }
    }
}
